### PR TITLE
Add warning on browser reload or window close

### LINKED ISSUE #48: Warn user if they have not saved their progress
When a user closes their window, they should be warned if they have not saved their progress.

image

### PR DESCRIPTION
**Pull request by yT0n1**
Fixes #48

### CODE REVIEW

**Comment by jan-ladleif** [comment]
Maybe this should be tied to the event bus, to only fire when the diagram is in a "dirty" state?
Otherwise, it might be annoying if I save the diagram and am still forced to confirm that I want to close the window.

**Comment by yT0n1** [comment]
I agree that that would probably be the better implementation. In that case, it would also make sense to add similar behavior to the "new diagram button" as well as the "open from disk" button. However, the implementation is quite a bit more work. We will have to write a module and inject it. As far as I remember we do not expose the event-bus to the outside. So I would prefer e merging the currently proposed solution and adding the better behavior at a later point in time.

**Comment by jan-ladleif** [comment]
The bpmn-js demo https://demo.bpmn.io/ manages to do it without injecting anything, by tapping into `modeler.on('commandStack.changed', modelUpdate);` and then setting a `dirty` flag which is cleared on save or load.

Maybe we can do it like that?
Seems relatively minimal and elegant. 🙂

**Comment by yT0n1** [comment]
I completely overlooked modeler.on() 😅. I made the necessary changes.

**Review by jan-ladleif — APPROVED** [review]
Nice enhancement! 🙂

**Pull request merged**
